@startuml

!theme carbon-gray
!include <C4/C4_Component>
!include common/c4-custom-rel.iuml
!include common/theme.iuml

title Схема с CDN, масштабированием API и Service Discovery
header «Мобильный мир»

Person(us_user, "Покупатель США", "")
Person(eu_user, "Покупатель ЕС", "")
Person(apac_user, "Покупатель APAC", "")

Boundary(cdn, "CDN", "") {
    Container(cdn.us, "CDN US Edge", "cdn", "PoP (США)")
    Container(cdn.eu, "CDN EU Edge", "cdn", "PoP (Европа)")
    Container(cdn.apac, "CDN APAC Edge", "cdn", "PoP (Азия)")
    cdn.us <.d.> cdn.eu : "Anycast / mesh
    cdn.eu <.d.> cdn.apac : Anycast / mesh
}

Boundary(gateway, "API Gateway", "Apache APISIX") {
    Container(api_gateway, "APISIX Gateway", "NGINX+Lua", "Балансировка HTTP(S)")
}

Boundary(consul, "Service Discovery", "HashiCorp Consul") {
    Container(consul.server1, "Consul Server 1", "consul")
    Container(consul.serverN, "Consul Server N", "consul")
    BiRel_R(consul.server1, consul.serverN, "Консенсус", "Raft Mesh")
    consul.server1 <.r.> consul.serverN : N >= 3
}
Interface " " as consul.api

Boundary(app, "Инстансы приложения") {
    Container_Boundary(app.instance1, "API Instance 1") {
        Container(app.agent1, "Consul Agent 1", "consul")
        Component(app.api1, "API", "FastAPI")
        Component(app.driver1, "Драйвер БД", "pymongo", "Балансирует нагрузку с помощью connection string с перечислением")
        Rel(app.api1, app.driver1, "Операции с БД", "Python Module")
    }
    Container_Boundary(app.instanceN, "API Instance N") {
        Container(app.agentN, "Consul Agent N", "consul")
        Component(app.apiN, "API", "FastAPI")
        Component(app.driverN, "Драйвер БД", "pymongo", "Балансирует нагрузку с помощью connection string с перечислением")
        Rel(app.apiN, app.driverN, "Операции с БД", "Python Module")
    }
    app.instance1 <.l.> app.instanceN : масштабирование
}
Interface " " as app.api

Boundary(cache, "Redis Master-Replica") {
    ContainerDb(redis.master, "Redis Master", "redis", "PRIMARY")
    ContainerDb(redis.1, "Redis Replica 1", "redis", "SECONDARY")
    ContainerDb(redis.n, "Redis Replica N", "redis", "SECONDARY")
    redis.1 <.l.> redis.n : масштабирование

  note as sentinel_note
    Узлы можно сопроводить
    Redis Sentinel, это даст:
    * Мониторинг здоровья Redis
    * Автоматический failover
    * Кворум для принятия решений
  end note
  sentinel_note .l. redis.master
  sentinel_note .d. redis.n
}

Boundary(router, "MongoDB Query Routers") {
    Container(router.1, "mongos-1", "MongoDB Router")
    Container(router.n, "mongos-N", "MongoDB Router")
    router.1 <.r.> router.n : масштабирование
}

Boundary(config, "Config Server Replica Set") {
    ContainerDb(config.master, "Config Server", "mongod", "PRIMARY")
    ContainerDb(config.1, "Config Server 1", "mongod", "SECONDARY")
    ContainerDb(config.N, "Config Server N", "mongod", "SECONDARY")
    config.1 <.r.> config.N : масштабирование
}

Boundary(shard1, "Shard 1 Replica Set") {
    ContainerDb(shard1.r1, "Shard 1-R-1", "mongod", "PRIMARY")
    ContainerDb(shard1.r2, "Shard 1-R-2", "mongod", "SECONDARY")
    ContainerDb(shard1.r3, "Shard 1-R-N", "mongod", "SECONDARY")
    shard1.r2 <.r.> shard1.r3 : масштабирование
}

Boundary(shard2, "Shard 2 Replica Set") {
    ContainerDb(shard2.r1, "Shard 2-R-1", "mongod", "PRIMARY")
    ContainerDb(shard2.r2, "Shard 2-R-2", "mongod", "SECONDARY")
    ContainerDb(shard2.r3, "Shard 2-R-N", "mongod", "SECONDARY")
    shard2.r2 <.r.> shard2.r3 : масштабирование
}

Rel_L(us_user, cdn.us, "Статика", "HTTPS",)
Rel_L(eu_user, cdn.eu, "Статика", "HTTPS",)
Rel_L(apac_user, cdn.apac, "Статика", "HTTPS",)
ARel(us_user, api_gateway, "Динамика", "HTTPS", $arrow="-d->>")
ARel(eu_user, api_gateway, "Динамика", "HTTPS", $arrow="-d->>")
ARel(apac_user, api_gateway, "Динамика", "HTTPS", $arrow="-d->>")
Lay_R(apac_user, eu_user)
Lay_R(eu_user, us_user)

ARel(cdn.apac, api_gateway, "Origin Pull\n(все Edge)", "HTTPS", $arrow="=d=|>")

Rel(api_gateway, app.api, "Балансируемые запросы", "HTTP")
Rel(app.api, app.api1, "", "")
Rel(app.api, app.apiN, "", "")

ARel(app.apiN, redis.master, "Запись в кеш\n(все инстансы)", "Redis", $arrow="=r=|>")
ARel(app.apiN, redis.1, "Чтение из кеша\n(все инстансы)", "Redis", $arrow="=r=|>")

ARel(app.driver1, router.1, "Запросы", "MongoDB", $arrow="---d->>")
ARel(app.driver1, router.n, "Запросы", "MongoDB", $arrow="---d->>")
ARel(app.driverN, router.1, "Запросы", "MongoDB", $arrow="---d->>")
ARel(app.driverN, router.n, "Запросы", "MongoDB", $arrow="---d->>")

Rel(api_gateway, consul.api, "Service Discovery API", "HTTP")
Rel(consul.api, consul.server1, "", "")
Rel(consul.api, consul.serverN, "", "")
Rel_L(app.api1, app.agent1, "Регистрация\nсервиса", "HTTP")
Rel_L(app.apiN, app.agentN, "Регистрация\nсервиса", "HTTP")

ARel(app.agent1, consul.serverN, "Catalog Sync\n(все инстансы)", "Serf/HTTP", $arrow="=l=|>")

ARel(router.1, config.master, "Получение\nметаданных", "MongoDB", $arrow="--d->>")
ARel(router.n, config.master, "Получение\nметаданных", "MongoDB", $arrow="--d->>")

ARel(router.1, shard1.r1, "Чтение\nЗапись", "MongoDB", $arrow="---d->>")
ARel(router.n, shard1.r1, "Чтение\nЗапись", "MongoDB", $arrow="---d->>")
ARel(router.1, shard2.r1, "Чтение\nЗапись", "MongoDB", $arrow="---d->>")
ARel(router.n, shard2.r1, "Чтение\nЗапись", "MongoDB", $arrow="---d->>")

Rel_D(config.master, config.1, "Репликация", "MongoDB")
Rel_D(config.master, config.N, "Репликация", "MongoDB")

Rel_D(shard1.r1, shard1.r2, "Репликация", "MongoDB")
Rel_D(shard1.r1, shard1.r3, "Репликация", "MongoDB")

Rel_D(shard2.r1, shard2.r2, "Репликация", "MongoDB")
Rel_D(shard2.r1, shard2.r3, "Репликация", "MongoDB")

Rel_D(redis.master, redis.1, "Репликация", "Redis")
Rel_D(redis.master, redis.n, "Репликация", "Redis")

' layout trick to space out the arrows
ARel(shard1.r1, config.master, "", "", $arrow="-[hidden]d->>")
ARel(shard2.r1, config.master, "", "", $arrow="-[hidden]d->>")

@enduml

