name: architecture-black_friday-sharding-repl-cache

services:
  # Config Server Replica 1 для хранения метаданных о шардах
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_configSrv
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data-1:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Config Server Replica 2
  configSrv2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_configSrv2
    restart: always
    ports:
      - "27021:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.11
    volumes:
      - config-data-2:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Config Server Replica 3
  configSrv3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_configSrv3
    restart: always
    ports:
      - "27022:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    volumes:
      - config-data-3:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Shard 1 Replica 1
  shard1-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_shard1-1
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    volumes:
      - shard1-data-1:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Shard 1 Replica 2
  shard1-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_shard1-2
    restart: always
    ports:
      - "27023:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.13
    volumes:
      - shard1-data-2:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Shard 1 Replica 3
  shard1-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_shard1-3
    restart: always
    ports:
      - "27024:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.14
    volumes:
      - shard1-data-3:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Shard 2 Replica 1
  shard2-1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_shard2-1
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    volumes:
      - shard2-data-1:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Shard 2 Replica 2
  shard2-2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_shard2-2
    restart: always
    ports:
      - "27025:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.15
    volumes:
      - shard2-data-2:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Shard 2 Replica 3
  shard2-3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_shard2-3
    restart: always
    ports:
      - "27026:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.16
    volumes:
      - shard2-data-3:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Роутер mongos
  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: repl_mongos_router
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos",
        "--configdb",
        "config_server/configSrv:27017,configSrv2:27017,configSrv3:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    depends_on:
      - configSrv
      - configSrv2
      - configSrv3
      - shard1-1
      - shard1-2
      - shard1-3
      - shard2-1
      - shard2-2
      - shard2-3
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  # Приложение pymongo_api
  pymongo_api:
    container_name: repl_pymongo_api
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
      - redis
    ports:
      - "8080:8080"
    networks:
      app-network:
        ipv4_address: 173.17.0.6
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"
    healthcheck:
      test:
        - CMD-SHELL
        - >
          python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/')"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:8.2.3-alpine
    container_name: repl_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      app-network:
        ipv4_address: 173.17.0.4
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  # Тесты приложения
  pymongo_api_test:
    container_name: sharding-repl-cache_api_test
    build:
      context: api_app_test
      dockerfile: Dockerfile
    depends_on:
      configSrv:
        condition: service_healthy
      configSrv2:
        condition: service_healthy
      configSrv3:
        condition: service_healthy
      shard1-1:
        condition: service_healthy
      shard1-2:
        condition: service_healthy
      shard1-3:
        condition: service_healthy
      shard2-1:
        condition: service_healthy
      shard2-2:
        condition: service_healthy
      shard2-3:
        condition: service_healthy
      mongos_router:
        condition: service_healthy
      pymongo_api:
        condition: service_healthy
    networks:
      app-network:
        ipv4_address: 173.17.0.5
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - test

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data-1:
  config-data-2:
  config-data-3:
  shard1-data-1:
  shard1-data-2:
  shard1-data-3:
  shard2-data-1:
  shard2-data-2:
  shard2-data-3:
